

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body style={{}}>{children}
        <h1 style={{ marginTop: '50px', display: 'flex', justifyContent: 'center' }}>The greatest website of all time (No one can see this since it's localhost lol)</h1>
        <div style={{ display: 'flex', justifyContent: 'space-between', width: '400px', margin: '0 auto' }}>
          <a href="/" style={{
            display: 'flex',
            marginTop: '20px',
            padding: '10px 20px',
            backgroundColor: '#333',
            color: 'white',
            textDecoration: 'none',
            borderRadius: '5px',
            width: '100px',
            height: '25px',
            justifyContent: 'center',
            alignItems: 'center'
          }}>Home</a>
          <a href="/dashboard" style={{
            display: 'flex',
            marginTop: '20px',
            padding: '10px 20px',
            backgroundColor: '#333',
            color: 'white',
            textDecoration: 'none',
            borderRadius: '5px',
            width: '100px',
            height: '25px',
            justifyContent: 'center',
            alignItems: 'center'
          }}>Dashboard</a>
          <a href="/settings" style={{
            display: 'flex',
            marginTop: '20px',
            padding: '10px 20px',
            backgroundColor: '#333',
            color: 'white',
            textDecoration: 'none',
            borderRadius: '5px',
            width: '100px',
            height: '25px',
            justifyContent: 'center',
            alignItems: 'center'
          }}>Settings</a>
        </div>
      </body>

    </html>
  );
}
